on:
  release:
    types:
      - created
    tags:
      - 'v*'

name: Create Release

jobs:
  releases:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm]
        exclude:
          - goos: darwin
            goarch: arm
    steps:
      - uses: actions/checkout@v2

      - name: Set RELEASE_VERSION
        id: get_version
        run: echo ::set-output name=RELEASE_VERSION::${GITHUB_REF/refs\/tags\//}

      - uses: wangyoucao577/go-release-action@v1.19
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: "1.16"
